############## style ##############
style:
  layout:
    max-width: "1125px" #最大宽度
  color:
    theme-main: "#1A98FF" # 主色调
    theme-secondary: "#DDF0FF" # 次色调
    text-main: "#333333" # 文字主色调
    text-secondary: "#898FA0" # 文字次色调


########## 关于主页的设置 ##########
# icon
icon: https://rmt.dogedoge.com/fetch/kurumit3/storage/avatar.jpg?fmt=webp #标签页图标
#  header
site_name: kurumit3.

menu:
  

## 本地搜索
search:
  open: false # 是否开启
  page: /search # 在上面页面上（通常命名为search）
  


# 自我介绍
intro:
  title: 有限的记忆，无限的梦.
  sub: '一个**不简单**的人，一个**叛逆**的高中生.爱[文学](https://blog.kurumit3.top/)，爱[音乐](https://music.163.com/#/user/home?id=1767196322)，爱[科技](https://kurumit3.top/)' # markdown语法
  avator: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #头像 暂时还没用到
  author: white #所有文章的默认作者

#联系方式
#更多图标：https://remixicon.com/
contact:
  Blogger:
    - https://kurumit3.top
    - ri-book-line
  Blogger2:
    - https://blog.kurumit3.top
    - ri-book-2-fill
  Github:
    - https://github.com/kurumiT3/
    - ri-github-line
  Email:
    - mailto:kurumiyout3@gmail.com
    - ri-mail-line
  Writter:
    - https://sspai.com/u/kurumit3/
    - ri-pencil-line
  Bilibili:
    - https://weibo.com/u/6482844382
    - ri-tv-line
  Netease:
    - https://music.163.com/#/user/home?id=1767196322
    - ri-netease-cloud-music-line
  Weibo:
    - https://weibo.com/u/6482844382
    - ri-weibo-line
  Twitter:
    - https://twitter.com/Nightma34781407
    - ri-twitter-line
  Instagram:  
    - https://www.instagram.com/nightmare_t3
    - ri-instagram-line

########## 关于文章的设置 ##########

# 文章toc索引栏设置
toc:
  max: 2 #最大
  min: 2 #最小

# 插件

# 评论系统设置
comments:
  valine:
    open: false # true | false 是否打开
    appid: #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  gitalk:
    open: false # true | false 是否打开
    owner:  #Github 用户名,
    repo:  #储存评论issue的github仓库名
    admin:  #Github 用户名
    clientID:  #`Github Application clientID`
    clientSecret: #`Github Application clientSecret`
  



############## 其他 ##############

# 页脚
footer: Power by [Hexo](http://hexo.io/) Theme by [White](https://github.com/FuShaoLei/hexo-theme-white) # markdown语法


